### ISSUE TITLE
Is this a valid use of 'yopq'?

### ISSUE THREAD

**Issue by tphinney** [TypeNetwork/Opentype-1.8-Axis-Proposal#66]
I have a variable font that has several axes, including weight, and contrast (yopq?). I am trying to decide if my contrast axis should be categorized as 'yopq', or if it is something different.

The base typeface is low contrast. Adjusting the yopq/contrast reduces the thickness of the horizontals, making it a high-contrast sans (like Radiant or the like).

At the boldest end, my yopq functions as everyone expects. The minimum thickness is about 2% of the em, and the maximum is visually equal to the vertical strokes, about 24% of the em (compared to the vertical strokes being about 28-29%, so no visual contrast).

BUT... at the lightest end of the weight axis, there is no longer room for the yopq to have any effect. The vertical strokes are 2% of the em. That's nearly as thin as I want a stroke to be in this typeface, so at minimum yopq horizontals are about the same (well, 1.8%, close enough). But I don't want a circus-like reverse contrast effect, so at the minimum weight, the maximum yopq is the same as the minimum!

Is this a legitimate way to have the yopq axis work? Or do I need to label this axis something else?

**Comment by dberlow** [comment]
Seems legit to me tphinney,

YOPQ is conceived independent of whether contrast exists stylistically, for optical purposes or not at all*, which are the main reasons for difference between x and y strokes, using that idea loosely to define what's heavier vs lighter in so many scrpts. 

In Latin, Radiant is an example of stylistic contrast, Helvetica, (with it's slight differences in V stroke, e.g.), of optical contrast. In many Sans, you see a tendency for optical contrast to grow with weight, and shrink with width. To grow towards small sizes, and shrink as they get larger. So in a 3-d variable space, YOPQ is active and useful when properly implemented both in development and for minor adjustments during use, for like if white-writer of the original CT rise from the dead, or when planning pedestrian crosswalk signage. 

And, e.g. if one only made a weight axis and YOPQ, and wanted to, they could program YOPQ to increase slightly as the point size reduced, to provide better rendering* or legibility for stylistically high contrast designs, as we demonstrate here:
https://variablefonts.typenetwork.com/topics/size/logo-example

Hope that helps!

Cheers,

**Comment by tphinney** [comment]
Yes, thanks!  :)

**Comment by davelab6** [comment]
Love this discussion. Thanks both!
