### ISSUE TITLE
Axis details have disappeared

### ISSUE THREAD

**Issue by ghost** [TypeNetwork/Opentype-1.8-Axis-Proposal#68]
The axis details and demo animations have disappeared from the main page. This seems to be due to a 307 redirect from Google Sheets, which causes a second request that no longer contains the `Origin` header for the cross-origin request.

However, even copying the CSV data into a local file doesn't solve the problem: the spreadsheet doesn't seem to be laid out the way the JS expects.

I'm sure I saw this page working in the last few months, and the spreadsheet hasn't changed in a few years. I'm stumped.

**Comment by dberlow** [comment]
I don’t think I edited this, but if you have a history of this we can find out?

**Comment by ghost** [comment]
Aha, I've found the [correct spreadsheet](https://docs.google.com/spreadsheets/d/1lZcLW7xo39zG3TTv6EK3iLs5t8OjWWPJv0lb9qEnsDE/edit?ts=5a1f1fb3#gid=2056122370). Will update.
